//
//  SettingsView.swift
//  AI Picture Book
//
//  Settings: Privacy Policy, Terms of Use, Contact Us (English).
//

import SwiftUI

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var selectedItem: SettingsItem?

    enum SettingsItem: String, CaseIterable {
        case privacy = "Privacy Policy"
        case terms = "Terms of Use"
        case contact = "Contact Us"
    }

    var body: some View {
        NavigationStack {
            List {
                ForEach(SettingsItem.allCases, id: \.self) { item in
                    Button(action: { selectedItem = item }) {
                        HStack {
                            Text(item.rawValue)
                                .foregroundStyle(AppTheme.textOnLight)
                            Spacer()
                            Image(systemName: "chevron.right")
                                .font(AppTheme.font(size: 14))
                                .foregroundStyle(AppTheme.textSecondary)
                        }
                    }
                    .buttonStyle(ClickSoundButtonStyle())
                }
            }
            .listStyle(.insetGrouped)
            .background(AppTheme.bgPrimary)
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .buttonStyle(ClickSoundButtonStyle())
                    .foregroundStyle(AppTheme.primary)
                }
            }
            .sheet(item: $selectedItem) { item in
                SettingsDetailView(item: item)
            }
        }
        .presentationDetents([.medium, .large])
    }
}

struct SettingsDetailView: View {
    @Environment(\.dismiss) private var dismiss
    let item: SettingsView.SettingsItem

    var body: some View {
        NavigationStack {
            ScrollView {
                Text(detailContent)
                    .font(AppTheme.font(size: 15))
                    .foregroundStyle(AppTheme.textOnLight)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(24)
            }
            .background(Color(.systemGroupedBackground))
            .navigationTitle(item.rawValue)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .buttonStyle(ClickSoundButtonStyle())
                    .foregroundStyle(AppTheme.primary)
                }
            }
        }
    }

    private var detailContent: String {
        switch item {
        case .privacy:
            return """
            Privacy Policy

            Last updated: 2025

            We respect your privacy. This app collects only the information you provide during onboarding (e.g., your child's name and age range) to personalize the experience. Story content is generated by AI and processed on our servers.

            We do not sell your personal information. Data is stored locally on your device where possible. For questions, use Contact Us in Settings.
            """
        case .terms:
            return """
            Terms of Use

            Last updated: 2025

            By using AI Story Book you agree to use the service for personal, non-commercial purposes. Generated stories and images are for your private use.

            We do not guarantee uninterrupted service. Subscription terms apply as shown at purchase. You may cancel through your App Store account settings.
            """
        case .contact:
            return """
            Contact Us

            For support, feedback, or privacy requests:

            Email: support@aistorybook.example.com

            We aim to respond within 2–3 business days.
            """
        }
    }
}

extension SettingsView.SettingsItem: Identifiable {
    var id: String { rawValue }
}

#Preview {
    SettingsView()
}
